// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	b0  *widget.Button
	b1  *widget.Button
	b2  *widget.Button
	b3  *widget.Button
	b4  *widget.Button
	b5  *widget.Button
	b6  *widget.Button
	b7  *widget.Button
	b8  *widget.Button
	b9  *widget.Button
	ba  *widget.Button
	bbc *widget.Button
	bbo *widget.Button
	bc  *widget.Button
	bd  *widget.Button
	bm  *widget.Button
	bp  *widget.Button
	bs  *widget.Button
	out *widget.Label
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.b0 = widget.NewButton("0", func() {})
	g.b1 = widget.NewButton("1", func() {})
	g.b2 = widget.NewButton("2", func() {})
	g.b3 = widget.NewButton("3", func() {})
	g.b4 = widget.NewButton("4", func() {})
	g.b5 = widget.NewButton("5", func() {})
	g.b6 = widget.NewButton("6", func() {})
	g.b7 = widget.NewButton("7", func() {})
	g.b8 = widget.NewButton("8", func() {})
	g.b9 = widget.NewButton("9", func() {})
	g.ba = widget.NewButton("+", func() {})
	g.bbc = widget.NewButton(")", func() {})
	g.bbo = widget.NewButton("(", func() {})
	g.bc = &widget.Button{Text: "C", Importance: 4, Alignment: 0, OnTapped: func() {}}
	g.bd = widget.NewButton("/", func() {})
	g.bm = widget.NewButton("*", func() {})
	g.bp = widget.NewButton(".", func() {})
	g.bs = widget.NewButton("-", func() {})
	g.out = widget.NewLabel("0")

	return container.NewGridWithColumns(1,
		g.out,
		container.NewGridWithColumns(4,
			g.bc,
			g.bbo,
			g.bbc,
			g.bd),
		container.NewGridWithColumns(4,
			g.b7,
			g.b8,
			g.b9,
			g.bm),
		container.NewGridWithColumns(4,
			g.b4,
			g.b5,
			g.b6,
			g.bs),
		container.NewGridWithColumns(4,
			g.b1,
			g.b2,
			g.b3,
			g.ba),
		container.NewGridWithColumns(2,
			container.NewGridWithColumns(2,
				g.b0,
				g.bp),
			&widget.Button{Text: "=", Importance: 1, Alignment: 0, OnTapped: g.evaluate}))
}